### ISSUE TITLE
Standardize repository

### ISSUE THREAD

**Issue by zenorocha** [molotovbliss/dracula-renoise-theme#3]
Hey @molotovbliss,

Just to follow-up on this: https://github.com/dracula/dracula-theme/issues/450 

Would you mind making the following changes?

* Rename repo from `dracula-renoise-theme` to `renoise`
* Rename image from `mb-dracula-renoise.png` to `screenshot.png`
* Use the same license as all the other themes: https://github.com/dracula/template/blob/master/LICENSE

Thanks!

**Comment by molotovbliss** [comment]
Hey @zenorocha changes requested updated in latest update (master). Let me know if need anything else updated/changed to conform to the standard.

* https://github.com/molotovbliss/renoise

Thanks! 🧛
